# Generated by Django 3.1.3 on 2020-11-30 02:23

from django.db import migrations, models
import django.db.models.deletion
import form_builders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatedForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('fields', form_builders.models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Created Form',
                'verbose_name_plural': 'Created Forms',
            },
        ),
        migrations.CreateModel(
            name='SubmittedForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', form_builders.models.JSONField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builders.createdforms')),
            ],
            options={
                'verbose_name': 'Submitted Form',
                'verbose_name_plural': 'Submitted Forms',
            },
        ),
    ]
